### ISSUE TITLE
Docker problem

### ISSUE THREAD

**Issue by MasterMartbob** [joway/burrow-dashboard#12]
I have tried many different ways to make the docker work but when I run the command
`docker run -e BURROW_BACKEND=http://192.168.32.10/v3/kafka joway/burrow-dashboard:latest`

I always get this output

```
user  nginx;
worker_processes  1;
worker_rlimit_nofile 65535;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    multi_accept on;
    worker_connections  15000;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    tcp_nopush     on;
    keepalive_timeout  65;
    gzip  on;

    server {
      listen 80;

      root /app;

      index index.html;

      location /v3 {
        proxy_pass                http://192.168.32.10:8000/v3/kafka;
        proxy_http_version        1.1;
        proxy_ignore_headers      Set-Cookie;
      }

      location / {
        try_files $uri $uri/ @rewrites;
      }

      location @rewrites {
        rewrite ^(.+)$ /index.html last;
      }

      location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        # Some basic cache-control for static files to be sent to the browser
        expires max;
        add_header Pragma public;
        add_header Cache-Control "public, must-revalidate, proxy-revalidate";
      }

    }
}
```

From there I can't send it to background with Ctrl+Z or kill it with Ctrl+C. I have to kill the docker conatiner from an other connection. I also can't access the web page with http://192.168.32.10:8080 or http://192.168.32.10:80.

I also tried different burrow backend with the same result 
http://192.168.32.10/v3 
http://192.168.32.10

I also tried building my local docker file but still the same result. Im on CentOs7 running a local docker burrow instance also a kafka and zookeeper docker. Burrow Api and Kafka work no problem.

What could I be doing wrong?

**Comment by joway** [comment]
you can use `docker run -d -e BURROW_BACKEND=http://192.168.32.10/v3/kafka joway/burrow-dashboard:latest`

it will set docker container to background .

**Comment by DivsDibs** [comment]
@MasterMartbob were you able to figure out the Web-Page Url?? and the BURROW_BACKEND..
I am running it in background, but can't figure out the Url...

Appreciate some help...
