### ISSUE TITLE
some vue errors displaying lag

### ISSUE THREAD

**Issue by marcosArruda** [joway/burrow-dashboard#13]
hey guys, I just runned the docker image, clicked on a small consumer-group and it worked flawless.

Then I clicked on a consumer-group consuming a big topic with lots of messages and 1000 partitions and nothing showed up on html. Doing an inspect on html got some vue errors trying to access timestamp from nulled offset. Here we go:

Seems like, js code is broken when loading big consumer-group metadata from burrow.
![screen shot 2018-05-08 at 20 19 32](https://user-images.githubusercontent.com/209169/39787832-b11c33ce-52fd-11e8-9151-a1d3955ad4cb.png)

**Comment by joway** [comment]
I see .   I will delete the timeout limit . Thanks for your issues ! @marcosArruda

**Comment by joway** [comment]
I have build a new image as `joway/burrow-dashboard:1.0.3`

**Comment by davispw** [comment]
Still getting this in 1.0.3.  Errors on null offset whenever consumer has been running for less than 10 minutes, because Burrow returns null in partition.offsets when it has collected less than 10 windows of data.
