### ISSUE TITLE
Docker Build Fails

### ISSUE THREAD

**Issue by jordanwilson230** [joway/burrow-dashboard#16]
Trying to build locally via docker.  While running ```npm install```, I error with the following:

```
sh: build/git-hooks/install.sh: No such file or directory
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! vue-material@1.0.0 postinstall: `sh build/git-hooks/install.sh`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the vue-material@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Perhaps my env. is incorrect?

**Comment by joway** [comment]
Hi , @jordanwilson230 

I found the same question at https://stackoverflow.com/questions/47777199/vue-material-postinstall-failed . I have fixed the problem in https://github.com/joway/burrow-dashboard/pull/17

**Comment by jordanwilson230** [comment]
Thanks, @joway. I'll give it a spin tomorrow morning and report back.

**Comment by jordanwilson230** [comment]
@joway working perfectly, thanks!
