### ISSUE TITLE
What is the Url to launch dashboard?

### ISSUE THREAD

**Issue by DivsDibs** [joway/burrow-dashboard#18]
Sorry, but couldn't figure out. Not in `README.md`

Tried using 
`node-1:10010/app/index.html` 
`node-1/app/index.html`
`burrow 1.1.0` is up at `http://node-1:8000`

I tried launching below command(s), but nothing worked
`docker run -e BURROW_BACKEND=http://node-1:8000 joway/burrow-dashboard:latest`
`docker run -e BURROW_BACKEND=http://node-1:8000  -d -p 80:80 joway/burrow-dashboard:latest`
`docker run -e BURROW_BACKEND=http://node-1:8000/v3/kafka joway/burrow-dashboard:latest`
`docker run -e BURROW_BACKEND=http://node-1:8000/v3/kafka  -d -p 80:80 joway/burrow-dashboard:latest`

Docker process seems to be up:
```
[root@nodeXYZ user]# docker ps
CONTAINER ID        IMAGE                           COMMAND             CREATED             STATUS              PORTS               NAMES
5375f7bda27c        joway/burrow-dashboard:latest   "./start.sh"        14 minutes ago      Up 14 minutes       80/tcp              lucid_johnson

```
When I log inside the docker container I can see: 
```
[root@node-1] sudo docker exec -it 5375f7bda27c /bin/sh [bash doesn't work for me]
/app # ls
index.html  start.sh    static
```
And finally I can see both Burrow and Docker container to be up and listening at 8000 and 80 respectively.
```
[root@node-1 logs]# netstat -nlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 node-1:10010       0.0.0.0:*               LISTEN      17857/docker-contai
tcp6       0      0 :::80                   :::*                    LISTEN      21266/docker-proxy
tcp6       0      0 :::8000                 :::*                    LISTEN      20027/Burrow

```

**Comment by DivsDibs** [comment]
@joway A little help is much appreciated. I see another post raising this same concern along with others and your comment didn't address the same. There is a single question here. Please advice..

**Comment by joway** [comment]
@DivsDibs  Hi , your can run the container by `docker run -e BURROW_BACKEND=http://node-1:8000 -d -p 80:80 joway/burrow-dashboard:latest`

your can see the dashboard on `http://node1:80`

PS: make sure that you can access the burrow backend api in your container's network . If can't , your can use `docker run --network host ...`

**Comment by dhaller-ttc** [comment]
For the docker container to find Burrow, assuming it is running on your localhost, you need to provide the IP address of the Burrow machine. On a mac, use ipconfig getifaddr en0.
Then pass this IP address as the host of the Burrow backend:
`docker run -e BURROW_BACKEND=http://<<your-host-ip>>:8000 -d -p 80:80 joway/burrow-dashboard:latest`
