### ISSUE TITLE
Still Getting TypeError on null Offsets in Consumer Views

### ISSUE THREAD

**Issue by jordanwilson230** [joway/burrow-dashboard#20]
>I don't think the error at Consumer.vue:56 has to do with request timeout

_Originally posted by @davispw in https://github.com/joway/burrow-dashboard/issues/13#issuecomment-409088155_

This seems true.  The issue in https://github.com/joway/burrow-dashboard/issues/13 was not fixed.  https://github.com/joway/burrow-dashboard/pull/14 only removed the timeout error.

The issue is regarding the TypeError which occurs when trying to read the timestamp of a null offset value.  Whenever this happens -- which, for me, is currently every consumer  -- the Consumer page renders nothing.

**Comment by joway** [comment]
https://github.com/joway/burrow-dashboard/commit/2427298f2fa6b3ac6d007dc5a49affc941a217d3

this pr has fixed the issues, I had build a new docker image and published as `joway/burrow-dashboard:1.0.4`

Thanks for your feedback!

**Comment by jordanwilson230** [comment]
@joway Awesome, thanks for the quick fix.  I will test now.

**Comment by jordanwilson230** [comment]
Looks good!
